### ISSUE TITLE
Add a way to support multiple `includeLevel`

### ISSUE THREAD

**Issue by MoOx** [Oktavilla/markdown-it-table-of-contents#1]
I was expecting that using `includeLevel: 3` would include both level 2 and level 3. Is there a way to achieve that with your plugin ?

**Comment by lexi** [comment]
Nope, there isn’t right now. We haven’t had the need for it yet. But feel free to make a PR :crown:

**Comment by MoOx** [comment]
I took another approach and did a new plugin that handle this and anchor link.

https://github.com/MoOx/markdown-it-toc-and-anchor
