### ISSUE TITLE
Default slugifier doesn't match markdown-it-anchor

### ISSUE THREAD

**Issue by map01ASCIIDOC10** [Oktavilla/markdown-it-table-of-contents#16]
Example: `## <span class="light">💀</span> Spiritual Skeleton`

- markdown-it-anchor id: **spiritual-skeleton**
- markdown-it-table-of-contents hash: **#span-classlightspan-spiritual-skeleton**

Doesn't match, bug?

**Comment by martinlissmyr** [comment]
Hi,

I've updated the tests with this case and it seems to yield the same results. I'm using 2.6.0 of markdown-it-anchor. Let me know if you can reproduce it or give me some information.
