### ISSUE TITLE
Cannot read property 'substr' of null

### ISSUE THREAD

**Issue by astoilkov** [Oktavilla/markdown-it-table-of-contents#17]
### Happens here:
```
parseInt(token.tag.substr(1, 1))
```

### Call stack:
```
"at renderChildsTokens (markdown-it-table-of-contents\\index.js:79:37)",
"at Object.md.renderer.rules.toc_body (markdown-it-table-of-contents\\index.js:66:12)",
"at Renderer.renderInline (markdown-it\\lib\\renderer.js:271:28)",
"at Renderer.render (markdown-it\\lib\\renderer.js:324:22)",
"at MarkdownIt.render (markdown-it\\lib\\index.js:539:24)",
```

### Reason:

I am not sure when it happens because this is an error report from a user which send the error without additional description.

**Comment by martinlissmyr** [comment]
> I am not sure when it happens because this is an error report from a user which send the error without additional description.

Then I can't help you. This does not mean anything without a context. Sorry.

**Comment by astoilkov** [comment]
Hi @martinlissmyr,

I successfully replicated the problem. Including [markdown-it-front-matter](https://github.com/craigdmckenna/markdown-it-front-matter) and `markdown-it-table-of-contents` breaks this package with the error described in the first post.

```markdown
---

---

[[toc]]
```

The reason for the issue is that YAML Front Matter is not represented with `tag` because it is excluded from the rendered content. markdown-it-table-of-contents fails because it doesn't check if the `token.tag` is defined.
