### ISSUE TITLE
Generated TOC is Wrapped Into a <p> and Validation Fails

### ISSUE THREAD

**Issue by ilyaigpetrov** [Oktavilla/markdown-it-table-of-contents#26]
Input:
```md
<nav>

[[toc]]

</nav>
```
Output:
```html
<!DOCTYPE html>
<html lang="en-US">
  <head>
    <title>Some title</title>
  </head>
  <body>
    <main>
      <nav>
        <p><div class="table-of-contents">...</div></p>
      </nav>
    </main>
  </body>
</html>
```
This output doesn't pass https://validator.w3.org/nu/#textarea because [\<p> can't contain block-level elements](https://stackoverflow.com/a/8696078/521957).

**Comment by martinlissmyr** [comment]
✅ 

If you have a fix, please submit a PR.

**Comment by ilyaigpetrov** [comment]
https://github.com/nagaozen/markdown-it-toc-done-right doesn't have this issue, you may look up their implementation, I don't have a PR.

**Comment by martinlissmyr** [comment]
As you're unwilling to contribute I will close this issue. Please feel free to reopen together with a PR with a proposed fix if you feel like it... 😄
