### ISSUE TITLE
Remove dependency on string@3.3.3 which has a security vulnerability (ReDos)

### ISSUE THREAD

**Issue by lgodmer** [Oktavilla/markdown-it-table-of-contents#29]
There is a security vulnerability in string@3.3.3 which causes it to be flagged by tools like snyk.
https://github.com/jprichardson/string.js/issues/212

The vulnerable methods in string@3.3.3 are not used by this project, however it still causes warnings from automated tooling. The issue has been discussed in the string.js repo for over 6 months and there is no traction there on a fix.

Consider switching to slugify (https://www.npmjs.com/package/slugify) instead, which does not have any open security vulnerabilities.

**Comment by martinlissmyr** [comment]
Fixed by https://github.com/Oktavilla/markdown-it-table-of-contents/releases/tag/v0.4.0 ... Thanks!

**Comment by lgodmer** [comment]
Thank you!
