### ISSUE TITLE
allow `includeLevel` to accept an array of levels

### ISSUE THREAD

**Issue by vieron** [Oktavilla/markdown-it-table-of-contents#3]
It would be nice to have this functionality to allow more detailed and customized tocs.

Example:

```
md.use(require('markdown-it-table-of-contents'), {
   includeLevel: [2, 3]
})
```

Expected output:

```
- h2
   - h3
   - h3
- h2
   - h3
   - h3
```

**Comment by mbforbes** [comment]
This would be really awesome. IMHO it would be the difference between this plugin being almost useful and fantastic! I hope the PR is merged soon!

**Comment by martinlissmyr** [comment]
Now available in https://github.com/Oktavilla/markdown-it-table-of-contents/releases/tag/v0.2.0

**Comment by nicolasartman** [comment]
@martinlissmyr would you mind publishing 0.2 to npm when you get the chance? This plugin is working great for me btw, thanks for making it!

**Comment by martinlissmyr** [comment]
@nicolasartman Oh, forgot to do that. Done now!

**Comment by nicolasartman** [comment]
Thank you!
