### ISSUE TITLE
Have a heading for the table of contents

### ISSUE THREAD

**Issue by GiridharanNarayanan** [Oktavilla/markdown-it-table-of-contents#31]
It would be better to have a heading like below, for the table of contents. I can raise a PR if you feel we can add this optional header for the TOC container.
![image](https://user-images.githubusercontent.com/40021266/43625480-e2d40d5a-970a-11e8-9bae-ce372ab6b533.png)

**Comment by GiridharanNarayanan** [comment]
Have raised a PR #32 . Let me know if you agree with the ask here.

**Comment by martinlissmyr** [comment]
Hi, thanks for contributing again.

However, I'm not convinced about the solution here. I think it's a bit too generic in that it's a div and not a header tag, and I think it's too specific in that you can't specify it's class name. On the other hand specifying all of those things in options would be messy and a bit overkill. 

What do you think about an alternative solution where you could just optionally inject any html before and after the toc (but inside the div). Not sure what you would use the after option for, but just for consistency and extensibility I guess. This way people could add whatever extra headers and footers they wanted.

What do you say?

**Comment by GiridharanNarayanan** [comment]
I agree. Having support for injecting HTML makes more sense. But since any string is a HTML, I assume we would not have to do any validation over the input. Let me know if you think otherwise. I shall update the PR with this approach and you can share your comments there.

**Comment by martinlissmyr** [comment]
Thanks for the contribution! This is now available in https://github.com/Oktavilla/markdown-it-table-of-contents/releases/tag/v0.4.2
