### ISSUE TITLE
Table of contents rendered incorrectly if no empty line is given before and after the [[toc]]

### ISSUE THREAD

**Issue by GiridharanNarayanan** [Oktavilla/markdown-it-table-of-contents#33]
**Example content:**
```
a
[[toc]]
b

# heading1
```

**Expected HTML:**
```
a
<div class="table-of-contents">
// list of headings
</div>
b

<h1>heading1</h1>
```

**Actual HTML is as below:** The TOC is getting rendered weirdly.
![image](https://user-images.githubusercontent.com/40021266/43655545-96353bba-976c-11e8-818b-0769f00050e4.png)

This is the sample runKit code I tried for this repro.
```
var MarkdownIt = require("markdown-it")
var md = new MarkdownIt();

md.use(require("markdown-it-anchor"));
md.use(require("markdown-it-table-of-contents"), {
markerPattern: /^\[\[toc\]\]/im
});

var content = "a\n" +
"[[toc]]\n" +
"b\n" +
"# Heading1\n" +
"## Sub heading 1\n" +
"Some even nicer text\n"
md.render(content);
```

I debugged and I could get the root cause. We are assuming that there could be no '\n' character before the [[toc]] syntax in the given state based on which we set the `state.pos`. Hence the index we set for the next processing is incorrect and changes depending upon the position of the first '\n' in state.src. It works in if there is a line gap before the [[toc]] and after it. 

I shall raise a PR trying to fix this issue.

**Comment by martinlissmyr** [comment]
Thanks! Fixed in https://github.com/Oktavilla/markdown-it-table-of-contents/releases/tag/v0.4.1
