### ISSUE TITLE
TOC regex pattern should be matched on the state.src only from the current position parsed

### ISSUE THREAD

**Issue by GiridharanNarayanan** [Oktavilla/markdown-it-table-of-contents#35]
**Issue:**
- Multiple TOCs equal to the number of  "[" in the same state.src as that of the state which contains [[toc]].
- This is because we do the regex match on the whole src instead of the substring of the src from the position which we are currently processing.

**Solution:**
- Match the regex only from the position we are currently processing in the state.
- I shall raise a PR if you ack this as an issue.

RunKit example. The highlighted "[" is causing the second TOC to be rendered.

![image](https://user-images.githubusercontent.com/40021266/44205842-6571c300-a175-11e8-9246-04611fa5645f.png)

**Comment by GiridharanNarayanan** [comment]
Have created a PR #36

**Comment by martinlissmyr** [comment]
Thanks! 👏
