### ISSUE TITLE
If the header is also a link, the href attribute in <a> will be wrong.

### ISSUE THREAD

**Issue by NevenLeung** [Oktavilla/markdown-it-table-of-contents#37]
If the header is a also link, not normal header, like `# header`, the href attribute in <a> will be wrong. In addition, the mark link in Plugins has some weird behaviors.

Please check [my demo](https://nevenleung.github.io/write-down/). The markdown testing source is just the source used in [markdown-it demo](https://markdown-it.github.io/). The 
screenshots are below. 

---

![toc](https://user-images.githubusercontent.com/18048923/46976612-8c5c5f00-d0fc-11e8-9724-6a20ff6c29fb.jpg)

---

![wrong-href](https://user-images.githubusercontent.com/18048923/46976860-2cb28380-d0fd-11e8-9d15-8c35924c61dc.jpg)

---

In my opinion, the link header should be treated differently. The markdown-it-anchor plugin handles it well by using the link text in `### [link text](url)` as the id attribute. The TOC plugin perhaps should threat it in this way.

**Comment by davibe** [comment]
same problem here. The TOC breaks if an header contains a link like

    ## [h2](somewhere)

I think this should be considered also

    ## a header linking [to](somewhere)

**Comment by martinlissmyr** [comment]
Closing as noone seems to want to do a fix for it. If you create a with PR with the necessary fixes I'd accept it.
