### ISSUE TITLE
Recognize IDs added by markdown-it-attrs

### ISSUE THREAD

**Issue by mathiasbynens** [Oktavilla/markdown-it-table-of-contents#38]
[markdown-it-attrs](https://github.com/arve0/markdown-it-attrs) makes it possible to define custom slugs for headers. For example,

```md
# This is an example header { #foo-bar }
```

…becomes…

```html
<h1 id="foo-bar">This is an example header</h1>
```

Is there a way to make markdown-it-table-of-contents recognize these pre-existing header IDs instead of making up its own?

**Comment by martinlissmyr** [comment]
Hi, unfortunately I don't have time to look into this at the moment... If you or anyone else feels like trying it out and see if they can figure it out it's most welcome...

**Comment by martinlissmyr** [comment]
Closing as noone seems to want to do a fix for it. If you create a with PR with the necessary fixes I'd accept it.
