### ISSUE TITLE
TOC with diacritics not working in IE

### ISSUE THREAD

**Issue by romcok** [Oktavilla/markdown-it-table-of-contents#40]
I think the problem is with encodeURIComponent in "slugify" option and IE can't handle this encoded string with diacritics after #. 
For example: `<a href="#z%C3%A1kladn%C3%A1-obrazovka">Základná obrazovka</a>`

**Comment by martinlissmyr** [comment]
Closing as noone seems to want to do a fix for it. If you create a with PR with the necessary fixes I'd accept it.
