### ISSUE TITLE
Conflicting with emojis

### ISSUE THREAD

**Issue by seahindeniz** [Oktavilla/markdown-it-table-of-contents#43]
If header contains emoji, plugin doesn't work as expected

**Expected result**
```html
<ul>
  <li>
    <a href="#h1-heading-8-)">h1 Heading 8-)</a>
  </li>
</ul>

<h1 id="h1-heading-8-)">h1 Heading <img class="emoji" draggable="false" alt="😎" src="https://twemoji.maxcdn.com/2/72x72/1f60e.png"></h1>
```
_OR_

**Expected result**
```html
<ul>
  <li>
    <a href="#h1-heading">h1 Heading 8-)</a>
  </li>
</ul>

<h1 id="h1-heading">h1 Heading <img class="emoji" draggable="false" alt="😎" src="https://twemoji.maxcdn.com/2/72x72/1f60e.png"></h1>
```

**Actual result**
```html
<ul>
  <li>
    <a href="#h1-heading-8-)">h1 Heading 8-)</a>
  </li>
</ul>

<h1 id="h1-heading">h1 Heading <img class="emoji" draggable="false" alt="😎" src="https://twemoji.maxcdn.com/2/72x72/1f60e.png"></h1>
```

**Comment by trolologuy** [comment]
Same issue with font awesome.
Here's the markdown:
`## <font-awesome-icon icon="language"/> Spoken Languages`
Results in this link:
`#font-awesome-icon-icon-language-spoken-languages`
Which is non-valid.
Everything between `< >`should probably be ignored.

**Comment by martinlissmyr** [comment]
Closing as noone seems to want to do a fix for it. If you create a with PR with the necessary fixes I'd accept it.
