### ISSUE TITLE
Support {{TOC}} pattern additionally to [[TOC]]

### ISSUE THREAD

**Issue by alexwall** [Oktavilla/markdown-it-table-of-contents#45]
This is a feature request to support `{{TOC}}` pattern additionally to `[[TOC]]`.

## Motivation

One major benefit of Markdown is, that it's just plaintext --> cross platform
It would be great to start working on Mac/PC (e.g. VSCode or Atom) and continue working with mobile devices like iPad etc.
The AppStore has already mobile Apps with great Markdown support like [1Writer](http://1writerapp.com) or [iA Writer](https://ia.net) , but this Apps are using `{{TOC}}` instead of `[[TOC]]`.

**Comment by martinlissmyr** [comment]
Hi. This already supported through the markerPattern option.

**Comment by alexwall** [comment]
Hi @martinlissmyr,

unfortunately not.
This code line rejects all tokens that doesn't start with with `[`

https://github.com/Oktavilla/markdown-it-table-of-contents/blob/7a796ca73fc89ada0ced504ddee09aed869c74a3/index.js#L26

**Comment by alexwall** [comment]
Additionally 

the default pattern could be `/^(\[|\{){2}toc(\]|\}){2}/im`  instead of `/^\[\[toc\]\]/im` 

to support  `{{TOC}}` and `[[TOC]]` natively

**Comment by martinlissmyr** [comment]
> This code line rejects all tokens that doesn't start with with

Ok, that seems like a "bug". I'd welcome a PR with a fix for that to start with.
