### ISSUE TITLE
It would be nice to have a more flexible content generation for links in toc

### ISSUE THREAD

**Issue by tenuki** [Oktavilla/markdown-it-table-of-contents#47]
I'd like to be able to have more control in "format" function (or other) to generate more porwerfull output. 

In particular, I'd like to be able to have the link to which the heading will point to available or the slug function used to generate it available.

**Comment by martinlissmyr** [comment]
Closing as noone seems to want to do a fix for it. If you create a with PR with the necessary fixes I'd accept it.

**Comment by tenuki** [comment]
> 
> 
> Closing as noone seems to want to do a fix for it. If you create a with PR with the necessary fixes I'd accept it.

It would be useful for me, so I've made it.  Thanks.
