### ISSUE TITLE
Interested in maintaining package

### ISSUE THREAD

**Issue by cpadilla** [Oktavilla/markdown-it-table-of-contents#53]
I'd be interested maintaining this package. I started my [blog](https://christofer.rocks) recently using Vuepress and GitHub pages, which I've been publishing to pretty consistently.

After comparing this package (which seems to be included with Vuepress by default) with the alternative, [vuepress-plugin-table-of-contents](https://github.com/vuepress/vuepress-plugin-table-of-contents), I decided I preferred this package's TOC because it's strictly markdown and it doesn't require me to customize a Vue component.

I've opened PR #52 as one of my first open-source contributions, which I think is significant considering how long I've been using GitHub for. Between that and PR #51, the two issues I had with this package have been fixed, so I'd be happy to maintain it moving forward. :)

**Comment by martinlissmyr** [comment]
Cool. Sounds good to me. 

Two things need to be done:
1. Transfer ownership of repo
2. Transfer ownership of npm package

Do you have a user on npmjs? if so, what's your username?

**Comment by cpadilla** [comment]
Yes, my username is rockzombie2 on there

**Comment by martinlissmyr** [comment]
You are now invited as a maintainer on Npm. Please confirm that you can access the package and then I will remove myself.

Before I can transfer the Github repo to you you have to remove your local branch. Github says the repo already exists otherwise. Please let me know when it's done and then I will finalise everything.

**Comment by cpadilla** [comment]
Okay, I can see I have access to the package on Npm and I deleted my fork of the repo on Github.

**Comment by martinlissmyr** [comment]
Ok, then I'll start the transfer. Hold on. :)

**Comment by martinlissmyr** [comment]
There we go. After you've accepted I'll remove myself from the NPM package and it's all yours!

**Comment by cpadilla** [comment]
Looks like the github invitation expired. Can you send it again?

**Comment by martinlissmyr** [comment]
Ok, check now.

**Comment by cpadilla** [comment]
Yep, looks good! Thanks for facilitating the transfer. I guess unless there's anything else that needs to be taken care of, we can wrap up this issue.

**Comment by martinlissmyr** [comment]
Yep. Thanks and good luck!

**Comment by martinlissmyr** [comment]
Oh, you should probably fix the references in the package.json and do a release so that NPM points to the right place.

**Comment by cpadilla** [comment]
Thanks, will do.
