### ISSUE TITLE
support typora style toc

### ISSUE THREAD

**Issue by shirayner** [Oktavilla/markdown-it-table-of-contents#56]
in typora, I user `[toc]` to display table of contents，but when use markdown-it-table-of-contents, I need user `[[toc]]`。

Is there any way to support typora style toc by using `[toc]`

**Comment by heartacker** [comment]
same  
we need this indeed

**Comment by cmaas** [comment]
This should work @shirayner @heartacker :
```js
md.use(markdownItTOC, {
    "markerPattern": /^\[toc\]/im
});
```
