### ISSUE TITLE
KaTeX Expressions aren't Included in Anchor Links

### ISSUE THREAD

**Issue by neurolag** [Oktavilla/markdown-it-table-of-contents#61]
Related: https://github.com/valeriangalliat/markdown-it-anchor/issues/112
Currently, KaTeX-expressions aren't part of the anchor-links generated by this plugin.

It'd be awesome to either have the option to add custom token-types to be included in anchor-links or to have `math_inline` added to this filter:
https://github.com/cmaas/markdown-it-table-of-contents/blob/62bfc75310056156b046d621167c998e8570b019/index.js#L72

Thanks for your great work 😄

**Comment by cmaas** [comment]
It's been a while, but I added the same option as in markdown-it-anchor. Thx for reporting.

**Comment by neurolag** [comment]
Awesome! Thank you so much 😄
